name: vuitton_web
description: "Vuitton Web."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  json_annotation: ^4.8.1
  dio: ^5.4.0
  font_awesome_flutter: ^10.6.0
  flutter_rating_bar: ^4.0.1
  animations: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  json_model: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: HanYiXueJun
      fonts:
        - asset: assets/fonts/HanYiXueJun.ttf
